export enum SortOrder {
  FILE_A_TO_Z = 'FILE_A_TO_Z',
  FILE_Z_TO_A = 'FILE_Z_TO_A',
  MODIFIED_NEW_TO_OLD = 'MODIFIED_NEW_TO_OLD',
  MODIFIED_OLD_TO_NEW = 'MODIFIED_OLD_TO_NEW',
  CREATED_NEW_TO_OLD = 'CREATED_NEW_TO_OLD',
  CREATED_OLD_TO_NEW = 'CREATED_OLD_TO_NEW',
}
